## PROBLEM SOURCE: https://rpubs.com/kateto/netviz

setwd("/Users/ritesh/pad-datascience/R/")
nodes <- read.csv("dataVisualization/data/Dataset1-Media-Example-NODES.csv", header=T, as.is=T)
links <- read.csv("dataVisualization/data/Dataset1-Media-Example-EDGES.csv", header=T, as.is=T)


#View(nodes)
#View(links)
head(nodes)
head(links)
## Find number of Nodes
nrow(nodes); length(unique(nodes$id))
nrow(links); nrow(unique(links[,c("from","to")]))

## Notice that there are more links than unique from-to combinations. That means we have cases
## in the data where there are multiple links between the same two nodes. We will collapse all links
## of the same type between the same two nodes by summing their weights(links[,3]), using aggregate() by
## “from”, “to”, & “type”(links[,-3]):
links <- aggregate(links[,3], links[,-3], sum)

## Sort the dataframe
links <- links[order(links$from, links$to),]

## Name the aggregated column as 'weight'
colnames(links)[4] <- "weight"
## Removed the randomized autogenerated ID column due sorting
rownames(links) <- NULL

## Dataset 2 - Matrix
nodes2 <- read.csv("R/dataVisualization/data/Dataset2-Media-User-Example-NODES.csv", header=T, as.is=T)
links2 <- read.csv("R/dataVisualization/data/Dataset2-Media-User-Example-EDGES.csv", header=T, row.names=1)

View(nodes2)
View(links2)
head(nodes2)
head(links2)

links2 <- as.matrix(links2)
dim(links2)
dim(nodes2)

install.packages("igraph")
library(igraph)
## we use igraph’s graph.data.frame function, which takes two data frames: d and vertices.
## - 'd' describes the edges of the network. Its first two columns are the IDs of the source and the target node for each edge.
## - 'vertices' starts with a column of node IDs. Any following columns are interpreted as node attributes
net <- graph.data.frame(links, nodes, directed=T)
net

E(net)        # The edges of the "net" object
V(net)        # The vertices of the "net" object
E(net)$type   # Edge attribute "type"
V(net)$media  # Vertex attribute "media"

# You can also manipulate the network matrix directly:
net[1,]
net[5,7]

plot(net)

## Remove Loops
simplify(net, remove.loops = T, remove.multiple = F)

plot(net, edge.arrow.size = .4, vertex.label = NA)

## Plot with node names
plot(net, edge.arrow.size=.2, edge.color="orange",
     vertex.color="gray50", vertex.frame.color="#ffffff",
     vertex.label=V(net)$media, vertex.label.color="black")

## Color the nodes based on Media Type
colrs <- c("gray50", "tomato", "gold")
V(net)$color <- colrs[V(net)$media.type]

plot(net, edge.arrow.size=.2, edge.color="orange",
     vertex.color=V(net)$color, vertex.frame.color="#ffffff",
     vertex.label=V(net)$media, vertex.label.color="black")

## Node size varies with size of audience
V(net)$size = V(net)$audience.size*0.6

## Now you want to know strength of Relationship based on Weight
E(net)$width <- E(net)$weight/6

## Regenerate the plot
plot(net, edge.arrow.size=.2, edge.color="orange",
     vertex.color=V(net)$color, vertex.frame.color="#ffffff",
     vertex.label=V(net)$media, vertex.label.color="black")

## Add Legend
legend(x=-1.5, y=-1.1, c("Newspaper","Television", "Online News"), pch=21,
       col="#777777", pt.bg=colrs, pt.cex=2, cex=.8, bty="n", ncol=1)


################## Plotting Parameters ####################

##### NODES	####
# vertex.color	 Node color
# vertex.frame.color	 Node border color
# vertex.shape	 One of 
# - “none”, 
# - “circle”, 
# - “square”, 
# - “csquare”, 
# - “rectangle”
# - “crectangle”, 
# - “vrectangle”, 
# - “pie”, 
# - “raster”, or 
# - “sphere”
# vertex.size	 Size of the node (default is 15)
# vertex.size2	 The second size of the node (e.g. for a rectangle)
# vertex.label	 Character vector used to label the nodes
# vertex.label.family	 Font family of the label (e.g.“Times”, “Helvetica”)
# vertex.label.font	 Font: 1 plain, 2 bold, 3, italic, 4 bold italic, 5 symbol
# vertex.label.cex	 Font size (multiplication factor, device-dependent)
# vertex.label.dist	 Distance between the label and the vertex
# vertex.label.degree	 The position of the label in relation to the vertex,
# where 0 right, “pi” is left, “pi/2” is below, and “-pi/2” is above

#### EDGES ####	 
# edge.color	 Edge color
# edge.width	 Edge width, defaults to 1
# edge.arrow.size	 Arrow size, defaults to 1
# edge.arrow.width	 Arrow width, defaults to 1
# edge.lty	 Line type, could be 0 or “blank”, 1 or “solid”, 2 or “dashed”,
# 3 or “dotted”, 4 or “dotdash”, 5 or “longdash”, 6 or “twodash”
# edge.label	 Character vector used to label edges
# edge.label.family	 Font family of the label (e.g.“Times”, “Helvetica”)
# edge.label.font	 Font: 1 plain, 2 bold, 3, italic, 4 bold italic, 5 symbol
# edge.label.cex	 Font size for edge labels
# edge.curved	 Edge curvature, range 0-1 (FALSE sets it to 0, TRUE to 0.5)
# arrow.mode	 Vector specifying whether edges should have arrows,
# possible values: 0 no arrow, 1 back, 2 forward, 3 both

#### OTHER ####
# margin	 Empty space margins around the plot, vector with length 4
# frame	 if TRUE, the plot will be framed
# main	 If set, adds a title to the plot
# sub	 If set, adds a subtitle to the plot




